### ISSUE TITLE
Failed to compile： Module not found

### ISSUE THREAD

**Issue by maplerichie** [TokenScript/token-negotiator#595]
Error
···
./node_modules/@tokenscript/token-negotiator/dist/wallet/WalletConnectV2Provider.js:37:0
Module not found: Package path ./dist/index.umd is not exported from package C:\wagmi_test\node_modules\@walletconnect\universal-provider (see exports field in C:\wagmi_test\node_modules\@walletconnect\universal-provider\package.json)

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@tokenscript/token-negotiator/dist/wallet/Web3WalletProvider.js
./node_modules/@tokenscript/token-negotiator/dist/client/index.js
./node_modules/@tokenscript/token-negotiator/dist/index.js
./src/pages/negotiator.tsx
···

Code
```
import { Client } from "@tokenscript/token-negotiator";

const tokenIssuers = [devconConfig];

  window.negotiator = new Client({
    type: "passive",
    issuers: tokenIssuers,
    offChainRedirectMode: undefined,
  });

  window.negotiator.on("tokens", (issuerTokens: any) => {
    let tokens: any = [];

    tokenIssuers.forEach((issuer: any) => {
      tokens.push(...issuerTokens[issuer.collectionID].tokens);
    });

    setTokens(tokens);
  });

  window.negotiator.on("error", (error: any, issuer: any) => {
    if (error.name === "POPUP_BLOCKED") {
      setRetryButton("Popup blocked");
    } else if (error.name === "USER_ABORT") {
      setRetryButton("Action aborted");
    } else {
      console.log(error);
      setRetryButton("An error occurred loading tokens");
    }
  });

  window.negotiator.on("tokens-selected", (tokens: any) => {
    // use tokens
    console.log("Token selected:", tokens);
  });

  window.negotiator.on("token-proof", (proof: any) => {
    // use proof
    console.log("Proof:", proof);
  });

  useEffect(() => {
    window.negotiator.negotiate();
  }, []);
```

**Comment by micwallace** [comment]
Hey @maplerichie I've release version 2.4.1 which should solve this issue. Let me know.

**Comment by maplerichie** [comment]
> Hey @maplerichie I've release version 2.4.1 which should solve this issue. Let me know.

2.4.1 still the same error
Tried change the import statement of `/dist/wallet/WalletConnectV2Provider.js:10:0` to `import UniversalProvider from "@walletconnect/universal-provider";` and it's worked!

![image](https://user-images.githubusercontent.com/10757316/226156894-5db14493-aa83-4ddf-b3cf-98f853fe644b.png)

**Comment by micwallace** [comment]
Hey @maplerichie thanks for letting us know. Can confirm this works in our example projects too. It wasn't with es5 target but after changing tsconfig.json to target es6 it's correctly picking up the es module. 

We'll release another patch version soon.

**Comment by nicktaras** [comment]
Hi @maplerichie,

Thanks so much for reaching out to us to raise this issue.

We've released a new patch, please let us know if you find any other issues.

https://www.npmjs.com/package/@tokenscript/token-negotiator?v=2.4.2
